baseURL: http://example.org/
languageCode: en-us
theme: sada
disableKinds:
  - taxonomy
  - taxonomyTerm
params:
  aboutme:
    description: Environmental Engineer and Geoscientist from Los Andes University, Bogotá, Colombia. I am a dynamic, hardworking and curious professional with a particular interest in research topics involving environmental health, environmental modeling, data science, Geographic Information Systems (GIS) and remote sensing.
  author: Martín Domínguez Durán
  copyright: 
  description: About me
  education:
    list:
      - college: Wageningen University & Research
        dates: 2016 - 2018
        degree: Masters in Degree 1
      - college: Los Andes University **Bogota, Colombia**
        dates: 2016 - 2021
        degree: B.Sc. Environmental Engineering
        # faculty: Faculty of Engineering
        thesis_link: 'https://repositorio.uniandes.edu.co/handle/1992/53124'
        thesis_title: Estudio exploratorio de radón residencial en Bogotá, Colombia y municipios aledaños
      - college: Los Andes University **Bogota, Colombia**
        # faculty: Faculty of Sciences
        dates: 2016 - 2021
        degree: B.Sc. Geosciences
        thesis_link: 'https://repositorio.uniandes.edu.co/handle/1992/53124'
        thesis_title: Estudio exploratorio de radón residencial en Bogotá, Colombia y municipios aledaños
    title: Education
  experiences:
    title: Experiences
  # hobbies:
    # list:
    #   - interest: GIS & RS
    #   - interest: Environmental health
    #   - interest: Environmental modeling
    #   - interest: Baking
    # title: Hobbies
  jobs:
    list:
      - company: Avinal S.A.
        dates: *March 2022* - *August 2022*
        link: 'https://avinal.com.co/'
        position: G.I.S. Advisor
      - company: Nutrición de Plantas S.A.
        dates: *August 2021* - *December 2021*
      #   details: 
#           list:
#             - Responsible of the making of ”Pilot study of Heavy Metal contamination in Avocado crops (Var. Hass) and
# feasibility analysis of Crosscheck methodology in Heavy Metal distribution”
#             - Support in the implementation of soil diagnostic services for agriculture (Nutricheck)
        # link: 'https://www.nutriciondeplantas.com.co/'
        # position: Technical advisor on *Agrosat* services
  language:
    list:
      - language: English
        level: Fluent
      - language: Bird
        level: Basic
    title: Languages
  name: example.org
  profile:
    name: Martín Domínguez Durán
    photo: images/profile.jpg
  projects:
    list:
      - description: Description of the *awesome* project 1
        title: Awesome Project 1
        url: '#'
      - description: Description of the **awesome** project 2. Lorem ipsum dolor sit
          amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
          et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
          ullamco laboris nisi ut aliquip ex ea commodo consequat.
        title: Awesome Project 2
        url: '#'
    title: Projects
  skills:
    list:
      - skill: Skill 1, Skill 2
        skillrating: 95
      - skill: Skill 3
        skillrating: 90
      - skill: Skill 4
        skillrating: 80
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: '#'
      - icon: ai ai-google-scholar
        title: Google Scholar
        url: '#'
      - icon: ai ai-researchgate
        title: ResearchGate
        url: '#'
    title: Links
  theme: light
  title: Sada Theme
  useResources: no
